server:
  port: 8080
  # 8889
  # port: {cipher}b177cfbafc485cda37b10e8019b90c2aa495da244f2b780fcfc4c6d7ccbeee3b

spring:
  rabbitmq:
    host: 192.168.1.41
    port: 5672
    username: '{cipher}d17903f286634b94f1b2dbceb2e8f656527270a83dcbd45e1fd1c416a5d55b5f'
    password: '{cipher}d17903f286634b94f1b2dbceb2e8f656527270a83dcbd45e1fd1c416a5d55b5f'
  application:
    name: web
  # freemarker 配置
  freemarker:
      allow-request-override: false
      # 缓存是否开启 true开启
      cache: false
      # 配合cache使用 cache true 这个需要写时间
      settings.template_update_delay: 0
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      request-context-attribute: ctx
  # jdbc
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/za_edu_cloud_platform_auth?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: '{cipher}b2e594c25f5ae31ac606ea5bd32786b212b4a46fcc3f2f88d277dc467819d743'
      password: '{cipher}b02762f55b725a58700eadc10c78f7e5469622ae3e0e3c6b8442677fdd9f4b5a'
  # 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

eureka:
  instance:
    # true 使用IP注册
    preferIpAddress: true
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    # fegin fallback
    enabled: true

mybatis:
  typeAliasesPackage: com.ssxu.entity
  mapperLocations: classpath:mapper/**/*.xml
  # 当返回值为空时 只是值为空 而不是把键直接去掉
  configuration:
    call-setters-on-nulls: true

htmlpath: http://localhost:8080
name: 徐石森
