server:
  port: 5000
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    web:
      path: /web/**
      serviceId: web
      # 加上这个访问的时候直接吧web就去掉了,转发地址直接就是zuul的地址加上后面的地址
      # 不false  localhost:5000/web/user/getName  后localhost:5000/user/getName 
      strip-prefix: false
    consumer:
      path: /consumer/**
      serviceId: consumer
