server:
  port: 5000
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    web:
      path: /web/**
      serviceId: web
      # 客户端配置context-path   的时候设置这个属性为false
      strip-prefix: false
    consumer:
      path: /consumer/**
      serviceId: consumer
